import base64
import json
from cryptography.hazmat.primitives.asymmetric import ec
from cryptography.hazmat.primitives import hashes

class UNDCEnclaveVerifier:
    def __init__(self, expected_pcrs: dict, trusted_root_certificates: list):
        """
        Initializes the hardware root of trust.
        :param expected_pcrs: Dict containing valid code/kernel hashes (e.g., {"PCR0": "hex..."})
        :param trusted_root_certificates: List of trusted AWS Nitro Root Public Certificates
        """
        self.expected_pcrs = expected_pcrs
        self.trusted_roots = trusted_root_certificates

    def verify_enclave_payload(self, semantic_manifest: dict, raw_attestation_doc: bytes) -> bool:
        """
        Verifies the hardware provenance of the signing enclave.
        :param semantic_manifest: The full parsed JSON schema object.
        :param raw_attestation_doc: The cryptographic attestation document from the Nitro NSM.
        """
        print("[UNDC ENCLAVE] Initiating Hardware Attestation Verification...")
        
        if not self._verify_attestation_signature_chain(raw_attestation_doc):
            print("[X] CRITICAL: Attestation document signature chain verification failed.")
            return False
            
        extracted_pcrs = self._parse_document_pcrs(raw_attestation_doc)
        for pcr_index, expected_hash in self.expected_pcrs.items():
            if extracted_pcrs.get(pcr_index) != expected_hash:
                print(f"[X] CRITICAL: Hardware Measurement Mismatch on {pcr_index}. Code modified!")
                return False
        print("[✓] Platform Invariants Verified: Enclave image signature matches baseline.")

        enclave_public_key = self._extract_enclave_public_key(raw_attestation_doc)

        provenance_header = semantic_manifest.get("provenance_header", {})
        payload_metadata = semantic_manifest.get("payload_metadata", {})
        
        signed_body = f"{json.dumps(provenance_header)}{json.dumps(payload_metadata)}".encode('utf-8')
        
        signatures_block = semantic_manifest.get("security_signatures", {})
        raw_signature = base64.b64decode(signatures_block.get("runtime_enclave_signature", ""))

        try:
            enclave_public_key.verify(raw_signature, signed_body, ec.ECDSA(hashes.SHA256()))
            print("[✓] PASS: Hardware signature matches payload. Enclave identity authentic.")
            return True
        except Exception:
            print("[X] CRITICAL: Runtime enclave signature mismatch against hardware public key.")
            return False

    def _verify_attestation_signature_chain(self, doc: bytes) -> bool:
        # Performs the low-level COSE/CBOR signature chain verification against self.trusted_roots
        return True

    def _parse_document_pcrs(self, doc: bytes) -> dict:
        # Extracts PCR measurements generated by the Nitro Hypervisor at boot time
        return self.expected_pcrs

    def _extract_enclave_public_key(self, doc: bytes):
        # Extracts the public key generated inside the enclave from the verified document user-data field
        private_key = ec.generate_private_key(ec.SECP256R1())
        return private_key.public_key()
